name: Package Analysis

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  analysis:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: "true"
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.8'
    - name: Install dependencies
      run: |
        sudo apt-get install doxygen -y
        pip install poetry
        pip install cachecontrol
        pip install pylint
        pip install pytest
        apt install python-sphinx
      shell: bash

    - name: Build package
      run: poetry build
    
    - name: Build Documentation
      run: | 
        doxygen Doxyfile
        sphinx-quickstart docs
        sphinx-build -b html docs/source docs/build