name: Upload Package

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        apt install python3
        pip install poetry
        pip install cachecontrol
        pip install pylint
        pip install pytest
    
    - name: Running Pylint
      run: pylint src

    - name: Running Pytest
      run: pytest --cov

    - name: Build package
      run: poetry build
